# author: Aysel Tandik, Anika Graupner
swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /BB:
    get:
      operationId: "ReadBB.read"
      tags:
        - "BB"
      summary: "The BoundingBox data structure supported by the server application"
      description: "Read the list of Boundig boxes"
      responses:
        200:
          description: "Successful read Bounding Boxlist operation"
          schema:
            type: "array"
            items:
              properties:
                Ausgabe:
                  type: "list"
                  type: "None"